config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  resources :workers
  resources :projects
  resources :searches, only: [:new]
  resources :contracts, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :worker
  belongs_to :project
  validates :worker_id, uniqueness: {scope: :project_id, message: "can't work twice in same project"}
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :contracts, dependent: :destroy
  has_many :workers, through: :contracts
  def find_contract(worker_id)
    Contract.where(worker_id: worker_id, project_id: self.id).first
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :contracts, dependent: :destroy
  has_many :projects, through: :contracts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  def create
    @projects = Project.all
    @workers = Worker.all
    unless params[:worker].nil?
      @contract = Contract.new(worker_id: params[:worker], project_id: params[:project_id])
    end
    unless params[:project].nil?
      @contract = Contract.new(project_id: params[:project], worker_id: params[:worker_id])
    end
    respond_to do |format|
      if @contract.save
        format.js
      else
        flash[:alert] = "#{@contract.errors.full_messages.join(', ')}"
        format.js {render js: "window.location='#{projects_path}'"}
        # format.js {redirect_to projects_path, turbolinks: false}
        # format.html {redirect_to projects_path, turbolinks: false, alert: "#{@contract.errors.full_messages.join(', ')}"}
      end
    end
  end

  def destroy
    @contract = Contract.find(params[:id])
    @contract.destroy
    flash[:notice] = "#{@contract.worker.name} removed from #{@contract.project.name}"
    redirect_to @contract.worker
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @workers = Worker.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/contracts/_js_projects.html.erb
<tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= link_to 'Show', project, class: 'btn btn-outline-success' %></td>
      <td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-outline-warning' %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
      <%= form_tag contracts_path, method: :post, remote: true, class: "navbar-form navbar-left search-form" do %>
      <%= hidden_field_tag 'project_id', project.id %>
        <td>
          <div class="input-group">
            <%= select_tag('worker', options_from_collection_for_select(@workers, "id", "name"), class: 'custom-select') %>
            <div class="input-group-append" data-turbolinks="true">
              <%= submit_tag 'Add', class: 'btn btn-outline-secondary', data: { disable_with: false } %>
            </div>
          </div>
        </td>
      <% end %>
    </tr>
  <% end %>
</tbody>

app/views/contracts/create.js.erb
$('#worker-added').remove();
$('#alerts').prepend("<div class='alert alert-success' id='worker-added' style='display:none'>Worker added to project</div>");
$('#worker-added').fadeIn(400);

app/views/layouts/_alerts.html.erb
<% if alert %>
  <div class="alert alert-warning">
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-info">
    <%= notice %>
  </div>
<% end %>

<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" data-turbolinks="false">
  <a class="navbar-brand" href="<%= root_path %>">WorkAssign ©</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= workers_path %>">Workers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= projects_path %>">Projects</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Create
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_worker_path %>">Worker</a>
          <a class="dropdown-item" href="<%= new_project_path %>">Project</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="new_search_path">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E19CP1A1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div id="alerts">
    <%= render 'layouts/alerts' %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
      <th>Add worker to project</th>
    </tr>
  </thead>
  <div id="js-projects">
    <%= render 'contracts/js_projects' %>
  </div>
</table>

<br>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Worker</th>
      <th>Working on</th>
    </tr>
  </thead>
  <tbody>
    <% @project.workers.each do |worker| %>
      <tr>
        <td><%= link_to worker.name, worker %></td>
        <td><%= worker.projects.count %> Projects</td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path, data: {turbolinks: false} %>

app/views/workers/_form.html.erb
<%= form_with(model: worker, local: true) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= link_to 'Show', worker, class: 'btn btn-outline-success' %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker), class: 'btn btn-outline-warning' %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path, class: 'btn btn-primary' %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @worker.name %></h1>
<table class="table">
  <thead>
    <tr>
      <th>
        Project
      </th>
      <th>
        Remove from project
      </th>
    </tr>
  </thead>
  <tbody>
    <% @worker.projects.each do |project| %>
      <tr>
        <td>
          <%= project.name %>
        </td>
        <td>
          <%= link_to 'X', contract_path(project.find_contract(@worker.id)), method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>